export const CREATE_SUBSCRIPTION_REQUEST = "CREATE_SUBSCRIPTION_REQUEST";
export const CREATE_SUBSCRIPTION_SUCCESS = "CREATE_SUBSCRIPTION_SUCCESS";
export const CREATE_SUBSCRIPTION_FAILURE = "CREATE_SUBSCRIPTION_FAILURE";

// Get User Subscription Actions
export const GET_USER_SUBSCRIPTION_REQUEST = "GET_USER_SUBSCRIPTION_REQUEST";
export const GET_USER_SUBSCRIPTION_SUCCESS = "GET_USER_SUBSCRIPTION_SUCCESS";
export const GET_USER_SUBSCRIPTION_FAILURE = "GET_USER_SUBSCRIPTION_FAILURE";

// Upgrade Subscription Actions
export const UPGRADE_SUBSCRIPTION_REQUEST = "UPGRADE_SUBSCRIPTION_REQUEST";
export const UPGRADE_SUBSCRIPTION_SUCCESS = "UPGRADE_SUBSCRIPTION_SUCCESS";
export const UPGRADE_SUBSCRIPTION_FAILURE = "UPGRADE_SUBSCRIPTION_FAILURE";
